package com.net355.models;

// Generated Dec 21, 2011 3:28:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ad generated by hbm2java
 */
@Entity
@Table(name = "ad", catalog = "net355")
public class Ad implements java.io.Serializable {

	private String adId;
	private Admin admin;
	private Syscode syscode;
	private String adType;
	private String adPath;
	private String adTitle;
	private String belongType;
	private String belongId;
	private Integer adLevel;
	private String adDesc;
	private String adHref;
	private Date addTime;
	private String state;

	public Ad() {
	}

	public Ad(String adId) {
		this.adId = adId;
	}

	public Ad(String adId, Admin admin, Syscode syscode, String adType,
			String adPath, String adTitle, String belongType, String belongId,
			Integer adLevel, String adDesc, String adHref, Date addTime,
			String state) {
		this.adId = adId;
		this.admin = admin;
		this.syscode = syscode;
		this.adType = adType;
		this.adPath = adPath;
		this.adTitle = adTitle;
		this.belongType = belongType;
		this.belongId = belongId;
		this.adLevel = adLevel;
		this.adDesc = adDesc;
		this.adHref = adHref;
		this.addTime = addTime;
		this.state = state;
	}

	@Id
	@Column(name = "ad_id", unique = true, nullable = false, length = 32)
	public String getAdId() {
		return this.adId;
	}

	public void setAdId(String adId) {
		this.adId = adId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ad_op_id")
	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sys_id")
	public Syscode getSyscode() {
		return this.syscode;
	}

	public void setSyscode(Syscode syscode) {
		this.syscode = syscode;
	}

	@Column(name = "ad_type", length = 2)
	public String getAdType() {
		return this.adType;
	}

	public void setAdType(String adType) {
		this.adType = adType;
	}

	@Column(name = "ad_path", length = 200)
	public String getAdPath() {
		return this.adPath;
	}

	public void setAdPath(String adPath) {
		this.adPath = adPath;
	}

	@Column(name = "ad_title", length = 100)
	public String getAdTitle() {
		return this.adTitle;
	}

	public void setAdTitle(String adTitle) {
		this.adTitle = adTitle;
	}

	@Column(name = "belong_type", length = 32)
	public String getBelongType() {
		return this.belongType;
	}

	public void setBelongType(String belongType) {
		this.belongType = belongType;
	}

	@Column(name = "belong_id", length = 2)
	public String getBelongId() {
		return this.belongId;
	}

	public void setBelongId(String belongId) {
		this.belongId = belongId;
	}

	@Column(name = "ad_level")
	public Integer getAdLevel() {
		return this.adLevel;
	}

	public void setAdLevel(Integer adLevel) {
		this.adLevel = adLevel;
	}

	@Column(name = "ad_desc", length = 500)
	public String getAdDesc() {
		return this.adDesc;
	}

	public void setAdDesc(String adDesc) {
		this.adDesc = adDesc;
	}

	@Column(name = "ad_href", length = 200)
	public String getAdHref() {
		return this.adHref;
	}

	public void setAdHref(String adHref) {
		this.adHref = adHref;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "add_time", length = 19)
	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	@Column(name = "state", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
