package com.net355.models;

// Generated Dec 21, 2011 3:28:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Attachment generated by hbm2java
 */
@Entity
@Table(name = "attachment", catalog = "net355")
public class Attachment implements java.io.Serializable {

	private String attId;
	private File file;
	private String belongId;
	private String attType;
	private Date addTime;
	private String attPath;
	private String state;

	public Attachment() {
	}

	public Attachment(String attId) {
		this.attId = attId;
	}

	public Attachment(String attId, File file, String belongId, String attType,
			Date addTime, String attPath, String state) {
		this.attId = attId;
		this.file = file;
		this.belongId = belongId;
		this.attType = attType;
		this.addTime = addTime;
		this.attPath = attPath;
		this.state = state;
	}

	@Id
	@Column(name = "att_id", unique = true, nullable = false, length = 32)
	public String getAttId() {
		return this.attId;
	}

	public void setAttId(String attId) {
		this.attId = attId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "file_id")
	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	@Column(name = "belong_id", length = 32)
	public String getBelongId() {
		return this.belongId;
	}

	public void setBelongId(String belongId) {
		this.belongId = belongId;
	}

	@Column(name = "att_type", length = 2)
	public String getAttType() {
		return this.attType;
	}

	public void setAttType(String attType) {
		this.attType = attType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "add_time", length = 19)
	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	@Column(name = "att_path", length = 500)
	public String getAttPath() {
		return this.attPath;
	}

	public void setAttPath(String attPath) {
		this.attPath = attPath;
	}

	@Column(name = "state", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
