package com.net355.models;

// Generated Dec 21, 2011 3:28:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(name = "log", catalog = "net355")
public class Log implements java.io.Serializable {

	private String logId;
	private String logType;
	private String logOpType;
	private String logClass;
	private String logOpId;
	private String logTarget;
	private String logDesc;
	private Date addTime;
	private String state;

	public Log() {
	}

	public Log(String logId) {
		this.logId = logId;
	}

	public Log(String logId, String logType, String logOpType, String logClass,
			String logOpId, String logTarget, String logDesc, Date addTime,
			String state) {
		this.logId = logId;
		this.logType = logType;
		this.logOpType = logOpType;
		this.logClass = logClass;
		this.logOpId = logOpId;
		this.logTarget = logTarget;
		this.logDesc = logDesc;
		this.addTime = addTime;
		this.state = state;
	}

	@Id
	@Column(name = "log_id", unique = true, nullable = false, length = 32)
	public String getLogId() {
		return this.logId;
	}

	public void setLogId(String logId) {
		this.logId = logId;
	}

	@Column(name = "log_type", length = 2)
	public String getLogType() {
		return this.logType;
	}

	public void setLogType(String logType) {
		this.logType = logType;
	}

	@Column(name = "log_op_type", length = 2)
	public String getLogOpType() {
		return this.logOpType;
	}

	public void setLogOpType(String logOpType) {
		this.logOpType = logOpType;
	}

	@Column(name = "log_class", length = 2)
	public String getLogClass() {
		return this.logClass;
	}

	public void setLogClass(String logClass) {
		this.logClass = logClass;
	}

	@Column(name = "log_op_id", length = 32)
	public String getLogOpId() {
		return this.logOpId;
	}

	public void setLogOpId(String logOpId) {
		this.logOpId = logOpId;
	}

	@Column(name = "log_target", length = 32)
	public String getLogTarget() {
		return this.logTarget;
	}

	public void setLogTarget(String logTarget) {
		this.logTarget = logTarget;
	}

	@Column(name = "log_desc", length = 400)
	public String getLogDesc() {
		return this.logDesc;
	}

	public void setLogDesc(String logDesc) {
		this.logDesc = logDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "add_time", length = 19)
	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	@Column(name = "state", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
