package com.net355.models;

// Generated Dec 21, 2011 3:28:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * News generated by hbm2java
 */
@Entity
@Table(name = "news", catalog = "net355")
public class News implements java.io.Serializable {

	private String newsId;
	private User user;
	private Admin admin;
	private Syscode syscode;
	private String newsType;
	private String newsTitle;
	private String newsContent;
	private String newsTag;
	private Date newsPubTime;
	private Date newsCheckTime;
	private Date addTime;
	private String state;

	public News() {
	}

	public News(String newsId) {
		this.newsId = newsId;
	}

	public News(String newsId, User user, Admin admin, Syscode syscode,
			String newsType, String newsTitle, String newsContent,
			String newsTag, Date newsPubTime, Date newsCheckTime, Date addTime,
			String state) {
		this.newsId = newsId;
		this.user = user;
		this.admin = admin;
		this.syscode = syscode;
		this.newsType = newsType;
		this.newsTitle = newsTitle;
		this.newsContent = newsContent;
		this.newsTag = newsTag;
		this.newsPubTime = newsPubTime;
		this.newsCheckTime = newsCheckTime;
		this.addTime = addTime;
		this.state = state;
	}

	@Id
	@Column(name = "news_id", unique = true, nullable = false, length = 32)
	public String getNewsId() {
		return this.newsId;
	}

	public void setNewsId(String newsId) {
		this.newsId = newsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "admin_id")
	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sys_id")
	public Syscode getSyscode() {
		return this.syscode;
	}

	public void setSyscode(Syscode syscode) {
		this.syscode = syscode;
	}

	@Column(name = "news_type", length = 2)
	public String getNewsType() {
		return this.newsType;
	}

	public void setNewsType(String newsType) {
		this.newsType = newsType;
	}

	@Column(name = "news_title", length = 200)
	public String getNewsTitle() {
		return this.newsTitle;
	}

	public void setNewsTitle(String newsTitle) {
		this.newsTitle = newsTitle;
	}

	@Column(name = "news_content")
	public String getNewsContent() {
		return this.newsContent;
	}

	public void setNewsContent(String newsContent) {
		this.newsContent = newsContent;
	}

	@Column(name = "news_tag", length = 100)
	public String getNewsTag() {
		return this.newsTag;
	}

	public void setNewsTag(String newsTag) {
		this.newsTag = newsTag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "news_pub_time", length = 19)
	public Date getNewsPubTime() {
		return this.newsPubTime;
	}

	public void setNewsPubTime(Date newsPubTime) {
		this.newsPubTime = newsPubTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "news_check_time", length = 19)
	public Date getNewsCheckTime() {
		return this.newsCheckTime;
	}

	public void setNewsCheckTime(Date newsCheckTime) {
		this.newsCheckTime = newsCheckTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "add_time", length = 19)
	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	@Column(name = "state", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
