package com.net355.models;

// Generated Dec 21, 2011 3:28:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notice generated by hbm2java
 */
@Entity
@Table(name = "notice", catalog = "net355")
public class Notice implements java.io.Serializable {

	private String noticeId;
	private Admin admin;
	private String noticeType;
	private String noticeDesc;
	private String noticeHref;
	private Date noticeEnd;
	private Date addTime;
	private String state;

	public Notice() {
	}

	public Notice(String noticeId) {
		this.noticeId = noticeId;
	}

	public Notice(String noticeId, Admin admin, String noticeType,
			String noticeDesc, String noticeHref, Date noticeEnd, Date addTime,
			String state) {
		this.noticeId = noticeId;
		this.admin = admin;
		this.noticeType = noticeType;
		this.noticeDesc = noticeDesc;
		this.noticeHref = noticeHref;
		this.noticeEnd = noticeEnd;
		this.addTime = addTime;
		this.state = state;
	}

	@Id
	@Column(name = "notice_id", unique = true, nullable = false, length = 32)
	public String getNoticeId() {
		return this.noticeId;
	}

	public void setNoticeId(String noticeId) {
		this.noticeId = noticeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "notice_op_id")
	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	@Column(name = "notice_type", length = 2)
	public String getNoticeType() {
		return this.noticeType;
	}

	public void setNoticeType(String noticeType) {
		this.noticeType = noticeType;
	}

	@Column(name = "notice_desc")
	public String getNoticeDesc() {
		return this.noticeDesc;
	}

	public void setNoticeDesc(String noticeDesc) {
		this.noticeDesc = noticeDesc;
	}

	@Column(name = "notice_href", length = 200)
	public String getNoticeHref() {
		return this.noticeHref;
	}

	public void setNoticeHref(String noticeHref) {
		this.noticeHref = noticeHref;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "notice_end", length = 19)
	public Date getNoticeEnd() {
		return this.noticeEnd;
	}

	public void setNoticeEnd(Date noticeEnd) {
		this.noticeEnd = noticeEnd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "add_time", length = 19)
	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	@Column(name = "state", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
