package com.net355.models;

// Generated Dec 21, 2011 3:28:17 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "net355")
public class Product implements java.io.Serializable {

	private String prodId;
	private User user;
	private Syscode syscode;
	private Brand brand;
	private String prodName;
	private String prodModel;
	private String prodDesc;
	private BigDecimal prodPrice;
	private String prodUnit;
	private String prodTag;
	private Date editTime;
	private String editIp;
	private Date addTime;
	private String state;

	public Product() {
	}

	public Product(String prodId) {
		this.prodId = prodId;
	}

	public Product(String prodId, User user, Syscode syscode, Brand brand,
			String prodName, String prodModel, String prodDesc,
			BigDecimal prodPrice, String prodUnit, String prodTag,
			Date editTime, String editIp, Date addTime, String state) {
		this.prodId = prodId;
		this.user = user;
		this.syscode = syscode;
		this.brand = brand;
		this.prodName = prodName;
		this.prodModel = prodModel;
		this.prodDesc = prodDesc;
		this.prodPrice = prodPrice;
		this.prodUnit = prodUnit;
		this.prodTag = prodTag;
		this.editTime = editTime;
		this.editIp = editIp;
		this.addTime = addTime;
		this.state = state;
	}

	@Id
	@Column(name = "prod_id", unique = true, nullable = false, length = 32)
	public String getProdId() {
		return this.prodId;
	}

	public void setProdId(String prodId) {
		this.prodId = prodId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sys_id")
	public Syscode getSyscode() {
		return this.syscode;
	}

	public void setSyscode(Syscode syscode) {
		this.syscode = syscode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "brand_id")
	public Brand getBrand() {
		return this.brand;
	}

	public void setBrand(Brand brand) {
		this.brand = brand;
	}

	@Column(name = "prod_name", length = 50)
	public String getProdName() {
		return this.prodName;
	}

	public void setProdName(String prodName) {
		this.prodName = prodName;
	}

	@Column(name = "prod_model", length = 50)
	public String getProdModel() {
		return this.prodModel;
	}

	public void setProdModel(String prodModel) {
		this.prodModel = prodModel;
	}

	@Column(name = "prod_desc", length = 65535)
	public String getProdDesc() {
		return this.prodDesc;
	}

	public void setProdDesc(String prodDesc) {
		this.prodDesc = prodDesc;
	}

	@Column(name = "prod_price", precision = 10)
	public BigDecimal getProdPrice() {
		return this.prodPrice;
	}

	public void setProdPrice(BigDecimal prodPrice) {
		this.prodPrice = prodPrice;
	}

	@Column(name = "prod_unit", length = 20)
	public String getProdUnit() {
		return this.prodUnit;
	}

	public void setProdUnit(String prodUnit) {
		this.prodUnit = prodUnit;
	}

	@Column(name = "prod_tag", length = 100)
	public String getProdTag() {
		return this.prodTag;
	}

	public void setProdTag(String prodTag) {
		this.prodTag = prodTag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "edit_time", length = 19)
	public Date getEditTime() {
		return this.editTime;
	}

	public void setEditTime(Date editTime) {
		this.editTime = editTime;
	}

	@Column(name = "edit_ip", length = 20)
	public String getEditIp() {
		return this.editIp;
	}

	public void setEditIp(String editIp) {
		this.editIp = editIp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "add_time", length = 19)
	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	@Column(name = "state", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
