package com.net355.models;

// Generated Dec 21, 2011 3:28:17 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Space generated by hbm2java
 */
@Entity
@Table(name = "space", catalog = "net355")
public class Space implements java.io.Serializable {

	private String spaceId;
	private User user;
	private BigDecimal spaceSize;
	private Date endTime;
	private Date addTime;
	private String state;

	public Space() {
	}

	public Space(String spaceId) {
		this.spaceId = spaceId;
	}

	public Space(String spaceId, User user, BigDecimal spaceSize, Date endTime,
			Date addTime, String state) {
		this.spaceId = spaceId;
		this.user = user;
		this.spaceSize = spaceSize;
		this.endTime = endTime;
		this.addTime = addTime;
		this.state = state;
	}

	@Id
	@Column(name = "space_id", unique = true, nullable = false, length = 32)
	public String getSpaceId() {
		return this.spaceId;
	}

	public void setSpaceId(String spaceId) {
		this.spaceId = spaceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "space_size", precision = 10)
	public BigDecimal getSpaceSize() {
		return this.spaceSize;
	}

	public void setSpaceSize(BigDecimal spaceSize) {
		this.spaceSize = spaceSize;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "add_time", length = 19)
	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	@Column(name = "state", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
