package com.net355.models;

// Generated Dec 21, 2011 3:28:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Syscode generated by hbm2java
 */
@Entity
@Table(name = "syscode", catalog = "net355")
public class Syscode implements java.io.Serializable {

	private String sysId;
	private String sysType;
	private String sysClass;
	private String sysFather;
	private String sysName;
	private String sysDesc;
	private String sysSign;
	private String state;
	private Set<Ad> ads = new HashSet<Ad>(0);
	private Set<User> users = new HashSet<User>(0);
	private Set<Product> products = new HashSet<Product>(0);
	private Set<News> newses = new HashSet<News>(0);
	private Set<Module> modules = new HashSet<Module>(0);

	public Syscode() {
	}

	public Syscode(String sysId) {
		this.sysId = sysId;
	}

	public Syscode(String sysId, String sysType, String sysClass,
			String sysFather, String sysName, String sysDesc, String sysSign,
			String state, Set<Ad> ads, Set<User> users, Set<Product> products,
			Set<News> newses, Set<Module> modules) {
		this.sysId = sysId;
		this.sysType = sysType;
		this.sysClass = sysClass;
		this.sysFather = sysFather;
		this.sysName = sysName;
		this.sysDesc = sysDesc;
		this.sysSign = sysSign;
		this.state = state;
		this.ads = ads;
		this.users = users;
		this.products = products;
		this.newses = newses;
		this.modules = modules;
	}

	@Id
	@Column(name = "sys_id", unique = true, nullable = false, length = 32)
	public String getSysId() {
		return this.sysId;
	}

	public void setSysId(String sysId) {
		this.sysId = sysId;
	}

	@Column(name = "sys_type", length = 2)
	public String getSysType() {
		return this.sysType;
	}

	public void setSysType(String sysType) {
		this.sysType = sysType;
	}

	@Column(name = "sys_class", length = 2)
	public String getSysClass() {
		return this.sysClass;
	}

	public void setSysClass(String sysClass) {
		this.sysClass = sysClass;
	}

	@Column(name = "sys_father", length = 32)
	public String getSysFather() {
		return this.sysFather;
	}

	public void setSysFather(String sysFather) {
		this.sysFather = sysFather;
	}

	@Column(name = "sys_name", length = 200)
	public String getSysName() {
		return this.sysName;
	}

	public void setSysName(String sysName) {
		this.sysName = sysName;
	}

	@Column(name = "sys_desc", length = 500)
	public String getSysDesc() {
		return this.sysDesc;
	}

	public void setSysDesc(String sysDesc) {
		this.sysDesc = sysDesc;
	}

	@Column(name = "sys_sign", length = 50)
	public String getSysSign() {
		return this.sysSign;
	}

	public void setSysSign(String sysSign) {
		this.sysSign = sysSign;
	}

	@Column(name = "state", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "syscode")
	public Set<Ad> getAds() {
		return this.ads;
	}

	public void setAds(Set<Ad> ads) {
		this.ads = ads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "syscode")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "syscode")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "syscode")
	public Set<News> getNewses() {
		return this.newses;
	}

	public void setNewses(Set<News> newses) {
		this.newses = newses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "syscode")
	public Set<Module> getModules() {
		return this.modules;
	}

	public void setModules(Set<Module> modules) {
		this.modules = modules;
	}

}
