package com.net355.models;

// Generated Dec 21, 2011 3:28:17 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "net355")
public class User implements java.io.Serializable {

	private String userId;
	private Syscode syscode;
	private String userAcc;
	private String userPwd;
	private String userType;
	private String userPwdQue;
	private String userPwdAns;
	private String userEmail;
	private String userName;
	private String country;
	private String province;
	private String city;
	private String dist;
	private String userAddress;
	private String zipcode;
	private String qq;
	private String msn;
	private String userPhone;
	private String userCell;
	private String userFax;
	private String userDomain;
	private BigDecimal accBalance;
	private BigDecimal accScore;
	private BigDecimal accSpace;
	private String accPwd;
	private Date editTime;
	private String editIp;
	private Date addTime;
	private String state;
	private Set<Viewlog> viewlogs = new HashSet<Viewlog>(0);
	private Set<Message> messagesForReceiverId = new HashSet<Message>(0);
	private Set<Recharge> recharges = new HashSet<Recharge>(0);
	private Set<Message> messagesForSenderId = new HashSet<Message>(0);
	private Set<Expense> expenses = new HashSet<Expense>(0);
	private Set<File> files = new HashSet<File>(0);
	private Set<Space> spaces = new HashSet<Space>(0);
	private Set<Product> products = new HashSet<Product>(0);
	private Set<Brand> brands = new HashSet<Brand>(0);
	private Set<Folder> folders = new HashSet<Folder>(0);
	private Set<News> newses = new HashSet<News>(0);

	public User() {
	}

	public User(String userId) {
		this.userId = userId;
	}

	public User(String userId, Syscode syscode, String userAcc, String userPwd,
			String userType, String userPwdQue, String userPwdAns,
			String userEmail, String userName, String country, String province,
			String city, String dist, String userAddress, String zipcode,
			String qq, String msn, String userPhone, String userCell,
			String userFax, String userDomain, BigDecimal accBalance,
			BigDecimal accScore, BigDecimal accSpace, String accPwd,
			Date editTime, String editIp, Date addTime, String state,
			Set<Viewlog> viewlogs, Set<Message> messagesForReceiverId,
			Set<Recharge> recharges, Set<Message> messagesForSenderId,
			Set<Expense> expenses, Set<File> files, Set<Space> spaces,
			Set<Product> products, Set<Brand> brands, Set<Folder> folders,
			Set<News> newses) {
		this.userId = userId;
		this.syscode = syscode;
		this.userAcc = userAcc;
		this.userPwd = userPwd;
		this.userType = userType;
		this.userPwdQue = userPwdQue;
		this.userPwdAns = userPwdAns;
		this.userEmail = userEmail;
		this.userName = userName;
		this.country = country;
		this.province = province;
		this.city = city;
		this.dist = dist;
		this.userAddress = userAddress;
		this.zipcode = zipcode;
		this.qq = qq;
		this.msn = msn;
		this.userPhone = userPhone;
		this.userCell = userCell;
		this.userFax = userFax;
		this.userDomain = userDomain;
		this.accBalance = accBalance;
		this.accScore = accScore;
		this.accSpace = accSpace;
		this.accPwd = accPwd;
		this.editTime = editTime;
		this.editIp = editIp;
		this.addTime = addTime;
		this.state = state;
		this.viewlogs = viewlogs;
		this.messagesForReceiverId = messagesForReceiverId;
		this.recharges = recharges;
		this.messagesForSenderId = messagesForSenderId;
		this.expenses = expenses;
		this.files = files;
		this.spaces = spaces;
		this.products = products;
		this.brands = brands;
		this.folders = folders;
		this.newses = newses;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false, length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sys_id")
	public Syscode getSyscode() {
		return this.syscode;
	}

	public void setSyscode(Syscode syscode) {
		this.syscode = syscode;
	}

	@Column(name = "user_acc", length = 30)
	public String getUserAcc() {
		return this.userAcc;
	}

	public void setUserAcc(String userAcc) {
		this.userAcc = userAcc;
	}

	@Column(name = "user_pwd", length = 32)
	public String getUserPwd() {
		return this.userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	@Column(name = "user_type", length = 2)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "user_pwd_que", length = 100)
	public String getUserPwdQue() {
		return this.userPwdQue;
	}

	public void setUserPwdQue(String userPwdQue) {
		this.userPwdQue = userPwdQue;
	}

	@Column(name = "user_pwd_ans", length = 100)
	public String getUserPwdAns() {
		return this.userPwdAns;
	}

	public void setUserPwdAns(String userPwdAns) {
		this.userPwdAns = userPwdAns;
	}

	@Column(name = "user_email", length = 100)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "user_name", length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "country", length = 32)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "province", length = 32)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "city", length = 32)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "dist", length = 32)
	public String getDist() {
		return this.dist;
	}

	public void setDist(String dist) {
		this.dist = dist;
	}

	@Column(name = "user_address", length = 200)
	public String getUserAddress() {
		return this.userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	@Column(name = "zipcode", length = 6)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "qq", length = 15)
	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	@Column(name = "msn", length = 50)
	public String getMsn() {
		return this.msn;
	}

	public void setMsn(String msn) {
		this.msn = msn;
	}

	@Column(name = "user_phone", length = 20)
	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	@Column(name = "user_cell", length = 12)
	public String getUserCell() {
		return this.userCell;
	}

	public void setUserCell(String userCell) {
		this.userCell = userCell;
	}

	@Column(name = "user_fax", length = 20)
	public String getUserFax() {
		return this.userFax;
	}

	public void setUserFax(String userFax) {
		this.userFax = userFax;
	}

	@Column(name = "user_domain", length = 50)
	public String getUserDomain() {
		return this.userDomain;
	}

	public void setUserDomain(String userDomain) {
		this.userDomain = userDomain;
	}

	@Column(name = "acc_balance", precision = 10)
	public BigDecimal getAccBalance() {
		return this.accBalance;
	}

	public void setAccBalance(BigDecimal accBalance) {
		this.accBalance = accBalance;
	}

	@Column(name = "acc_score", precision = 10)
	public BigDecimal getAccScore() {
		return this.accScore;
	}

	public void setAccScore(BigDecimal accScore) {
		this.accScore = accScore;
	}

	@Column(name = "acc_space", precision = 10)
	public BigDecimal getAccSpace() {
		return this.accSpace;
	}

	public void setAccSpace(BigDecimal accSpace) {
		this.accSpace = accSpace;
	}

	@Column(name = "acc_pwd", length = 32)
	public String getAccPwd() {
		return this.accPwd;
	}

	public void setAccPwd(String accPwd) {
		this.accPwd = accPwd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "edit_time", length = 19)
	public Date getEditTime() {
		return this.editTime;
	}

	public void setEditTime(Date editTime) {
		this.editTime = editTime;
	}

	@Column(name = "edit_ip", length = 20)
	public String getEditIp() {
		return this.editIp;
	}

	public void setEditIp(String editIp) {
		this.editIp = editIp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "add_time", length = 19)
	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	@Column(name = "state", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Viewlog> getViewlogs() {
		return this.viewlogs;
	}

	public void setViewlogs(Set<Viewlog> viewlogs) {
		this.viewlogs = viewlogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userByReceiverId")
	public Set<Message> getMessagesForReceiverId() {
		return this.messagesForReceiverId;
	}

	public void setMessagesForReceiverId(Set<Message> messagesForReceiverId) {
		this.messagesForReceiverId = messagesForReceiverId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Recharge> getRecharges() {
		return this.recharges;
	}

	public void setRecharges(Set<Recharge> recharges) {
		this.recharges = recharges;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userBySenderId")
	public Set<Message> getMessagesForSenderId() {
		return this.messagesForSenderId;
	}

	public void setMessagesForSenderId(Set<Message> messagesForSenderId) {
		this.messagesForSenderId = messagesForSenderId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Expense> getExpenses() {
		return this.expenses;
	}

	public void setExpenses(Set<Expense> expenses) {
		this.expenses = expenses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<File> getFiles() {
		return this.files;
	}

	public void setFiles(Set<File> files) {
		this.files = files;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Space> getSpaces() {
		return this.spaces;
	}

	public void setSpaces(Set<Space> spaces) {
		this.spaces = spaces;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Brand> getBrands() {
		return this.brands;
	}

	public void setBrands(Set<Brand> brands) {
		this.brands = brands;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Folder> getFolders() {
		return this.folders;
	}

	public void setFolders(Set<Folder> folders) {
		this.folders = folders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<News> getNewses() {
		return this.newses;
	}

	public void setNewses(Set<News> newses) {
		this.newses = newses;
	}

}
