package com.net355.models;

// Generated Dec 21, 2011 3:28:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Viewlog generated by hbm2java
 */
@Entity
@Table(name = "viewlog", catalog = "net355")
public class Viewlog implements java.io.Serializable {

	private String vlogId;
	private User user;
	private Integer vlogNum;
	private String vlogType;
	private String vlogTarget;
	private Date addTime;
	private String state;

	public Viewlog() {
	}

	public Viewlog(String vlogId) {
		this.vlogId = vlogId;
	}

	public Viewlog(String vlogId, User user, Integer vlogNum, String vlogType,
			String vlogTarget, Date addTime, String state) {
		this.vlogId = vlogId;
		this.user = user;
		this.vlogNum = vlogNum;
		this.vlogType = vlogType;
		this.vlogTarget = vlogTarget;
		this.addTime = addTime;
		this.state = state;
	}

	@Id
	@Column(name = "vlog_id", unique = true, nullable = false, length = 32)
	public String getVlogId() {
		return this.vlogId;
	}

	public void setVlogId(String vlogId) {
		this.vlogId = vlogId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "vlog_num")
	public Integer getVlogNum() {
		return this.vlogNum;
	}

	public void setVlogNum(Integer vlogNum) {
		this.vlogNum = vlogNum;
	}

	@Column(name = "vlog_type", length = 2)
	public String getVlogType() {
		return this.vlogType;
	}

	public void setVlogType(String vlogType) {
		this.vlogType = vlogType;
	}

	@Column(name = "vlog_target", length = 32)
	public String getVlogTarget() {
		return this.vlogTarget;
	}

	public void setVlogTarget(String vlogTarget) {
		this.vlogTarget = vlogTarget;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "add_time", length = 19)
	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	@Column(name = "state", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
