package com.net355.models;

// Generated Dec 21, 2011 3:28:17 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Expense generated by hbm2java
 */
@Entity
@Table(name = "expense", catalog = "net355")
public class Expense implements java.io.Serializable {

	private String expenseId;
	private User user;
	private BigDecimal expenseAmount;
	private BigDecimal expenseScore;
	private String expenseType;
	private String expenseTarget;
	private Date addTime;
	private String state;

	public Expense() {
	}

	public Expense(String expenseId) {
		this.expenseId = expenseId;
	}

	public Expense(String expenseId, User user, BigDecimal expenseAmount,
			BigDecimal expenseScore, String expenseType, String expenseTarget,
			Date addTime, String state) {
		this.expenseId = expenseId;
		this.user = user;
		this.expenseAmount = expenseAmount;
		this.expenseScore = expenseScore;
		this.expenseType = expenseType;
		this.expenseTarget = expenseTarget;
		this.addTime = addTime;
		this.state = state;
	}

	@Id
	@Column(name = "expense_id", unique = true, nullable = false, length = 32)
	public String getExpenseId() {
		return this.expenseId;
	}

	public void setExpenseId(String expenseId) {
		this.expenseId = expenseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "expense_amount", precision = 10)
	public BigDecimal getExpenseAmount() {
		return this.expenseAmount;
	}

	public void setExpenseAmount(BigDecimal expenseAmount) {
		this.expenseAmount = expenseAmount;
	}

	@Column(name = "expense_score", precision = 10)
	public BigDecimal getExpenseScore() {
		return this.expenseScore;
	}

	public void setExpenseScore(BigDecimal expenseScore) {
		this.expenseScore = expenseScore;
	}

	@Column(name = "expense_type", length = 2)
	public String getExpenseType() {
		return this.expenseType;
	}

	public void setExpenseType(String expenseType) {
		this.expenseType = expenseType;
	}

	@Column(name = "expense_target", length = 32)
	public String getExpenseTarget() {
		return this.expenseTarget;
	}

	public void setExpenseTarget(String expenseTarget) {
		this.expenseTarget = expenseTarget;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "add_time", length = 19)
	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	@Column(name = "state", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
