package com.net355.models;

// Generated Dec 21, 2011 3:28:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Folder generated by hbm2java
 */
@Entity
@Table(name = "folder", catalog = "net355")
public class Folder implements java.io.Serializable {

	private String folderId;
	private User user;
	private String folderName;
	private String folderDesc;
	private String folderType;
	private Integer folderAmount;
	private String folderPwd;
	private Date editTime;
	private String editIp;
	private Date addTime;
	private String state;
	private Set<File> files = new HashSet<File>(0);

	public Folder() {
	}

	public Folder(String folderId) {
		this.folderId = folderId;
	}

	public Folder(String folderId, User user, String folderName,
			String folderDesc, String folderType, Integer folderAmount,
			String folderPwd, Date editTime, String editIp, Date addTime,
			String state, Set<File> files) {
		this.folderId = folderId;
		this.user = user;
		this.folderName = folderName;
		this.folderDesc = folderDesc;
		this.folderType = folderType;
		this.folderAmount = folderAmount;
		this.folderPwd = folderPwd;
		this.editTime = editTime;
		this.editIp = editIp;
		this.addTime = addTime;
		this.state = state;
		this.files = files;
	}

	@Id
	@Column(name = "folder_id", unique = true, nullable = false, length = 32)
	public String getFolderId() {
		return this.folderId;
	}

	public void setFolderId(String folderId) {
		this.folderId = folderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "folder_name", length = 32)
	public String getFolderName() {
		return this.folderName;
	}

	public void setFolderName(String folderName) {
		this.folderName = folderName;
	}

	@Column(name = "folder_desc", length = 500)
	public String getFolderDesc() {
		return this.folderDesc;
	}

	public void setFolderDesc(String folderDesc) {
		this.folderDesc = folderDesc;
	}

	@Column(name = "folder_type", length = 2)
	public String getFolderType() {
		return this.folderType;
	}

	public void setFolderType(String folderType) {
		this.folderType = folderType;
	}

	@Column(name = "folder_amount")
	public Integer getFolderAmount() {
		return this.folderAmount;
	}

	public void setFolderAmount(Integer folderAmount) {
		this.folderAmount = folderAmount;
	}

	@Column(name = "folder_pwd", length = 32)
	public String getFolderPwd() {
		return this.folderPwd;
	}

	public void setFolderPwd(String folderPwd) {
		this.folderPwd = folderPwd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "edit_time", length = 19)
	public Date getEditTime() {
		return this.editTime;
	}

	public void setEditTime(Date editTime) {
		this.editTime = editTime;
	}

	@Column(name = "edit_ip", length = 20)
	public String getEditIp() {
		return this.editIp;
	}

	public void setEditIp(String editIp) {
		this.editIp = editIp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "add_time", length = 19)
	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	@Column(name = "state", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "folder")
	public Set<File> getFiles() {
		return this.files;
	}

	public void setFiles(Set<File> files) {
		this.files = files;
	}

}
