package com.net355.models;

// Generated Dec 21, 2011 3:28:17 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Recharge generated by hbm2java
 */
@Entity
@Table(name = "recharge", catalog = "net355")
public class Recharge implements java.io.Serializable {

	private String rechargeId;
	private User user;
	private String rechargeIp;
	private BigDecimal rechargeAmount;
	private BigDecimal rechargeScore;
	private String rechargeType;
	private String rechargeMd5;
	private Date addTime;
	private String state;

	public Recharge() {
	}

	public Recharge(String rechargeId) {
		this.rechargeId = rechargeId;
	}

	public Recharge(String rechargeId, User user, String rechargeIp,
			BigDecimal rechargeAmount, BigDecimal rechargeScore,
			String rechargeType, String rechargeMd5, Date addTime, String state) {
		this.rechargeId = rechargeId;
		this.user = user;
		this.rechargeIp = rechargeIp;
		this.rechargeAmount = rechargeAmount;
		this.rechargeScore = rechargeScore;
		this.rechargeType = rechargeType;
		this.rechargeMd5 = rechargeMd5;
		this.addTime = addTime;
		this.state = state;
	}

	@Id
	@Column(name = "recharge_id", unique = true, nullable = false, length = 32)
	public String getRechargeId() {
		return this.rechargeId;
	}

	public void setRechargeId(String rechargeId) {
		this.rechargeId = rechargeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "recharge_ip", length = 20)
	public String getRechargeIp() {
		return this.rechargeIp;
	}

	public void setRechargeIp(String rechargeIp) {
		this.rechargeIp = rechargeIp;
	}

	@Column(name = "recharge_amount", precision = 10)
	public BigDecimal getRechargeAmount() {
		return this.rechargeAmount;
	}

	public void setRechargeAmount(BigDecimal rechargeAmount) {
		this.rechargeAmount = rechargeAmount;
	}

	@Column(name = "recharge_score", precision = 10)
	public BigDecimal getRechargeScore() {
		return this.rechargeScore;
	}

	public void setRechargeScore(BigDecimal rechargeScore) {
		this.rechargeScore = rechargeScore;
	}

	@Column(name = "recharge_type", length = 2)
	public String getRechargeType() {
		return this.rechargeType;
	}

	public void setRechargeType(String rechargeType) {
		this.rechargeType = rechargeType;
	}

	@Column(name = "recharge_md5", length = 200)
	public String getRechargeMd5() {
		return this.rechargeMd5;
	}

	public void setRechargeMd5(String rechargeMd5) {
		this.rechargeMd5 = rechargeMd5;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "add_time", length = 19)
	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	@Column(name = "state", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
