package com.betball.models;

// Generated Dec 1, 2011 1:37:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BetGambler generated by hbm2java
 */
@Entity
@Table(name = "bet_gambler", catalog = "betball")
public class BetGambler implements java.io.Serializable {

	private Integer id;
	private String eid;
	private String name;
	private int balance;
	private String state;
	private Date regtime;
	private String password;
	private Set<BetTransaction> betTransactions = new HashSet<BetTransaction>(0);
	private Set<BetRecharge> betRecharges = new HashSet<BetRecharge>(0);

	public BetGambler() {
	}

	public BetGambler(String eid, String name, int balance, String state,
			Date regtime) {
		this.eid = eid;
		this.name = name;
		this.balance = balance;
		this.state = state;
		this.regtime = regtime;
	}

	public BetGambler(String eid, String name, int balance, String state,
			Date regtime, String password, Set<BetTransaction> betTransactions,
			Set<BetRecharge> betRecharges) {
		this.eid = eid;
		this.name = name;
		this.balance = balance;
		this.state = state;
		this.regtime = regtime;
		this.password = password;
		this.betTransactions = betTransactions;
		this.betRecharges = betRecharges;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "eid", nullable = false, length = 7)
	public String getEid() {
		return this.eid;
	}

	public void setEid(String eid) {
		this.eid = eid;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "balance", nullable = false)
	public int getBalance() {
		return this.balance;
	}

	public void setBalance(int balance) {
		this.balance = balance;
	}

	@Column(name = "state", nullable = false, length = 1)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "regtime", nullable = false, length = 19)
	public Date getRegtime() {
		return this.regtime;
	}

	public void setRegtime(Date regtime) {
		this.regtime = regtime;
	}

	@Column(name = "password", length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "betGambler")
	public Set<BetTransaction> getBetTransactions() {
		return this.betTransactions;
	}

	public void setBetTransactions(Set<BetTransaction> betTransactions) {
		this.betTransactions = betTransactions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "betGambler")
	public Set<BetRecharge> getBetRecharges() {
		return this.betRecharges;
	}

	public void setBetRecharges(Set<BetRecharge> betRecharges) {
		this.betRecharges = betRecharges;
	}

}
