package com.betball.models;

// Generated Dec 1, 2011 1:37:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BetMatch generated by hbm2java
 */
@Entity
@Table(name = "bet_match", catalog = "betball")
public class BetMatch implements java.io.Serializable {

	private Integer id;
	private Date matchdate;
	private Date matchtime;
	private String hometeam;
	private String awayteam;
	private String lega;
	private String final_;
	private String state;
	private String result;
	private Date gettime;
	private Set<BetTransaction> betTransactions = new HashSet<BetTransaction>(0);
	private Set<BetPosition> betPositions = new HashSet<BetPosition>(0);

	public BetMatch() {
	}

	public BetMatch(Date matchdate, Date matchtime, String hometeam,
			String awayteam, String lega, String final_, String state) {
		this.matchdate = matchdate;
		this.matchtime = matchtime;
		this.hometeam = hometeam;
		this.awayteam = awayteam;
		this.lega = lega;
		this.final_ = final_;
		this.state = state;
	}

	public BetMatch(Date matchdate, Date matchtime, String hometeam,
			String awayteam, String lega, String final_, String state,
			String result, Date gettime, Set<BetTransaction> betTransactions,
			Set<BetPosition> betPositions) {
		this.matchdate = matchdate;
		this.matchtime = matchtime;
		this.hometeam = hometeam;
		this.awayteam = awayteam;
		this.lega = lega;
		this.final_ = final_;
		this.state = state;
		this.result = result;
		this.gettime = gettime;
		this.betTransactions = betTransactions;
		this.betPositions = betPositions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "matchdate", nullable = false, length = 10)
	public Date getMatchdate() {
		return this.matchdate;
	}

	public void setMatchdate(Date matchdate) {
		this.matchdate = matchdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "matchtime", nullable = false, length = 19)
	public Date getMatchtime() {
		return this.matchtime;
	}

	public void setMatchtime(Date matchtime) {
		this.matchtime = matchtime;
	}

	@Column(name = "hometeam", nullable = false, length = 50)
	public String getHometeam() {
		return this.hometeam;
	}

	public void setHometeam(String hometeam) {
		this.hometeam = hometeam;
	}

	@Column(name = "awayteam", nullable = false, length = 50)
	public String getAwayteam() {
		return this.awayteam;
	}

	public void setAwayteam(String awayteam) {
		this.awayteam = awayteam;
	}

	@Column(name = "lega", nullable = false, length = 50)
	public String getLega() {
		return this.lega;
	}

	public void setLega(String lega) {
		this.lega = lega;
	}

	@Column(name = "final", nullable = false, length = 50)
	public String getFinal_() {
		return this.final_;
	}

	public void setFinal_(String final_) {
		this.final_ = final_;
	}

	@Column(name = "state", nullable = false, length = 1)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "result", length = 5)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "gettime", length = 10)
	public Date getGettime() {
		return this.gettime;
	}

	public void setGettime(Date gettime) {
		this.gettime = gettime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "betMatch")
	public Set<BetTransaction> getBetTransactions() {
		return this.betTransactions;
	}

	public void setBetTransactions(Set<BetTransaction> betTransactions) {
		this.betTransactions = betTransactions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "betMatch")
	public Set<BetPosition> getBetPositions() {
		return this.betPositions;
	}

	public void setBetPositions(Set<BetPosition> betPositions) {
		this.betPositions = betPositions;
	}

}
