package com.betball.models;

// Generated Dec 1, 2011 1:37:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BetPosition generated by hbm2java
 */
@Entity
@Table(name = "bet_position", catalog = "betball")
public class BetPosition implements java.io.Serializable {

	private Integer id;
	private BetMatch betMatch;
	private String position;
	private Date postime;

	public BetPosition() {
	}

	public BetPosition(BetMatch betMatch, String position, Date postime) {
		this.betMatch = betMatch;
		this.position = position;
		this.postime = postime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "match_id", nullable = false)
	public BetMatch getBetMatch() {
		return this.betMatch;
	}

	public void setBetMatch(BetMatch betMatch) {
		this.betMatch = betMatch;
	}

	@Column(name = "position", nullable = false, length = 50)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "postime", nullable = false, length = 19)
	public Date getPostime() {
		return this.postime;
	}

	public void setPostime(Date postime) {
		this.postime = postime;
	}

}
