package com.betball.models;

// Generated Dec 1, 2011 1:37:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BetRecharge generated by hbm2java
 */
@Entity
@Table(name = "bet_recharge", catalog = "betball")
public class BetRecharge implements java.io.Serializable {

	private Integer id;
	private BetGambler betGambler;
	private int amount;
	private Date chargetime;

	public BetRecharge() {
	}

	public BetRecharge(BetGambler betGambler, int amount, Date chargetime) {
		this.betGambler = betGambler;
		this.amount = amount;
		this.chargetime = chargetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gambler_id", nullable = false)
	public BetGambler getBetGambler() {
		return this.betGambler;
	}

	public void setBetGambler(BetGambler betGambler) {
		this.betGambler = betGambler;
	}

	@Column(name = "amount", nullable = false)
	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "chargetime", nullable = false, length = 19)
	public Date getChargetime() {
		return this.chargetime;
	}

	public void setChargetime(Date chargetime) {
		this.chargetime = chargetime;
	}

}
