package com.betball.models;

// Generated Dec 1, 2011 1:37:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BetTransaction generated by hbm2java
 */
@Entity
@Table(name = "bet_transaction", catalog = "betball")
public class BetTransaction implements java.io.Serializable {

	private Integer id;
	private BetGambler betGambler;
	private BetMatch betMatch;
	private Date bettime;
	private int bet;
	private String result;
	private String state;

	public BetTransaction() {
	}

	public BetTransaction(BetGambler betGambler, BetMatch betMatch,
			Date bettime, int bet, String result) {
		this.betGambler = betGambler;
		this.betMatch = betMatch;
		this.bettime = bettime;
		this.bet = bet;
		this.result = result;
	}

	public BetTransaction(BetGambler betGambler, BetMatch betMatch,
			Date bettime, int bet, String result, String state) {
		this.betGambler = betGambler;
		this.betMatch = betMatch;
		this.bettime = bettime;
		this.bet = bet;
		this.result = result;
		this.state = state;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gambler_id", nullable = false)
	public BetGambler getBetGambler() {
		return this.betGambler;
	}

	public void setBetGambler(BetGambler betGambler) {
		this.betGambler = betGambler;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "match_id", nullable = false)
	public BetMatch getBetMatch() {
		return this.betMatch;
	}

	public void setBetMatch(BetMatch betMatch) {
		this.betMatch = betMatch;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bettime", nullable = false, length = 19)
	public Date getBettime() {
		return this.bettime;
	}

	public void setBettime(Date bettime) {
		this.bettime = bettime;
	}

	@Column(name = "bet", nullable = false)
	public int getBet() {
		return this.bet;
	}

	public void setBet(int bet) {
		this.bet = bet;
	}

	@Column(name = "result", nullable = false, length = 1)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "state", length = 1)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
